### ISSUE TITLE
OpenSSL extension is missing

### ISSUE THREAD

**Issue by oscarnevarezleal** [paketo-buildpacks/php-dist#188]
## What happened?

I'm building a builder that uses _php-dist_ and _php-composer_, some of my buildpacks require OpenSSL to be installed but it's by default.

* What were you attempting to do?

> 1 - To fetch HTTPS-secured content using _file_get_contents_ function.
> 2 - Install missing dependencies (not originally present, but detected later) using composer require 

* What did you expect to happen?

> - I can instruct the builder to include the extension during the build process ( related to #118 )
> - The script can be executed without errors.

* What was the actual behavior? Please provide log output, if possible.

> OpenSSL is not installed

a) my script
```
warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
```

b) composer (called later)
```
[builder]   composer require --dev brianium/paratest
[builder]   The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.  
```

## Build Configuration

```
# [...]
[[order]]
  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.2.0"
  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    version = "0.1.2"
  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.138"
```

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using?

```
pack version 0.17.0+git-d9cb4e7.build-2045
```

* What buildpacks are you using? Please include versions.
```

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php-dist"
  version = "0.2.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php-web"
  version = "0.0.138"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php-composer"
  version = "0.1.2"

```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

_docker.io/paketobuildpacks/builder:full-cf_

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ x ] I have included log output.
* [ x ] The log output includes an error message.
* [ x ] I have included steps for reproduction.

**Comment by arjun024** [comment]
See this [Paketo PHP buildpacks doc](https://paketo.io/docs/buildpacks/language-family-buildpacks/php/#configuring-custom-ini-files), you should be able to create an ini file with `extension=openssl.so` located at `<APP-ROOT>/.php.ini.d/<any-file-name>.ini` to instruct the buildpack to load a module. If that didn't help you, please provide an app I can reproduce the issue.

**Comment by oscarnevarezleal** [comment]
Thanks, @arjun024.
That made the trick.
