### ISSUE TITLE
Php version - improper constraint 

### ISSUE THREAD

**Issue by oscarnevarezleal** [paketo-buildpacks/php-dist#201]
## What happened?

* What were you attempting to do?
- - I'm trying to use php buildpack with a Laravel application, but I got an error regarding the PHP version constraint specified for it.

* What did you expect to happen?
- - Php buildpack successfully accepts the candidate version suggested in composer.lock file

* What was the actual behavior? Please provide log output, if possible.

```
Paketo PHP Buildpack 0.2.0
  Resolving PHP version
    Candidate version sources (in priority order):
      composer.lock -> "^7.3|^8.0"
      <unknown>     -> ""

improper constraint: ^7.3|^8.0
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

> pack-v0.17.0-linux.tgz

* What buildpacks are you using? Please include versions.
```
pass: paketo-buildpacks/php-dist@0.2.0
pass: paketo-buildpacks/php-composer@0.1.2
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

```
# This comand runs before packing
pack config default-builder paketobuildpacks/builder:full
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## How to reproduce
Use the following script.

```
#!/usr/bin/env bash

set -eu
set -o pipefail

pack config default-builder paketobuildpacks/builder:full

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php composer-setup.php --filename=composer
sudo chmod +x composer
sudo mv composer /usr/local/bin/composer
php -r "unlink('composer-setup.php');"

# Create a new laravel project here
composer create-project laravel/laravel laravel-base

pushd laravel-base

// ...

pack build test-laraboot-app --path . \
--buildpack paketo-buildpacks/php-dist \
--buildpack paketo-buildpacks/php-composer \
--builder paketobuildpacks/builder:full \
--clear-cache --verbose

popd

```

## Checklist

* [ x ] I have included log output.
* [ x ] The log output includes an error message.
* [ x ] I have included steps for reproduction.

**Comment by arjun024** [comment]
@oscarnevarezleal I believe this was an issue with upstream packit and was solved with packit v0.7. Do you still the have the same issue with the latest php buildpack?

**Comment by oscarnevarezleal** [comment]
@arjun024 It worked. Thank you.

**Comment by arjun024** [comment]
Great. Closing issue.
