### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by dwillist** [paketo-buildpacks/php-dist#33]
This buildpack is missing any integration testing using `pack` and this buildpack to produce a container image.

We should add some simple integration tests that just assert that the `php` binary is added to an output image & that it correctly functions on the bionic stack.

**Comment by arjun024** [comment]
Why bionic?
#43 adds integration tests, but the runner script `integration.sh` tests it on `cflinuxfs3`.
https://github.com/paketo-buildpacks/php-dist/blob/3ee02a05030e692be7d43e550ecdf6c01e1d5422/scripts/integration.sh#L50-L57
