### ISSUE TITLE
php cli is not in $PATH

### ISSUE THREAD

**Issue by till** [paketo-buildpacks/php-dist#425]
## Expected Behavior

I can use the `php` cli inside my image:

```php
<?php
#!/usr/bin/env php
echo "Hello world";
```

## Current Behavior

```
/layers/paketo-buildpacks_php-dist/php/bin/php -v
PHP 8.1.7 (cli) (built: Jun 15 2022 09:21:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
cnb@c2a50c734a25:/workspace$ echo $PATH
/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cnb@c2a50c734a25:/workspace$ php -v
bash: php: command not found
```

## Possible Solution

Add the layer to the `PATH`, or install in a location that is in `PATH` already.

## Steps to Reproduce

Discovered this while fiddling with paketo-buildpacks/composer-install#46

## Motivations

Lots of projects distribute command line tools that rely on the `php` (cli) to be in `PATH`. These are broken now.

In addition, there are so-called phars, which are php apps distributed as an executable archive. They also rely on the cli to be in `PATH`.

**Comment by sophiewigmore** [comment]
`php` is made available in `PATH` during the build, and at launch-time so it's available to other buildpack processes. You can see it if you built a PHP app with the buildpacks, and then overwrite the start command when starting the container like so:
```
 docker run -it --entrypoint launcher <image name> env
```
You're right that it's not available on the final image. Your reasoning for including it seems reasonable though. Could you possibly provide a more concrete example of an app which needs access to PHP on the final image?

**Comment by thitch97** [comment]
@till could you provide some more concrete reproduction steps for this issue? I see your PR but I'm still a bit confused about why it's necessary. The lifecycle should automatically add the `bin` directory within the PHP layer to the path and so far I'm able to use the `php` CLI in a pack-built app image just fine.

**Comment by till** [comment]
@thitch97 It's not in the launch environment though. So php console applications don't run. Am I missing something?

**Comment by thitch97** [comment]
How were you trying to invoke the app/inspect the launch environment? I'm able to use the CLI and see `<layer>/php/bin` on the `PATH` this way:

```
 ‣ docker run -it --entrypoint=launcher console /bin/bash
cnb@b47d1c5e5128:/workspace$ php -v
PHP 8.0.23 (cli) (built: Sep  1 2022 14:21:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.23, Copyright (c) Zend Technologies
cnb@b47d1c5e5128:/workspace$ env | grep PATH
LD_LIBRARY_PATH=/layers/paketo-buildpacks_php-dist/php/lib
PATH=/layers/paketo-buildpacks_php-dist/php/sbin:/layers/paketo-buildpacks_php-dist/php/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The `--entrypoint=launcher` bit might be what you're missing

**Comment by robdimsdale** [comment]
I was able to shell out to the php CLI from within a sample app as follows:

app.php:

```php
<?php
#!/usr/bin/env php
echo "Hello world";
?>
```

Procfile:

```
web: php app.php
```

Build and run the app with:
```
❯ pack build --builder paketobuildpacks/builder:full php-cli-app
❯ docker run -it php-cli-app
Hello world
```

I know this is using the full php buildpack, not just php-dist in isolation, but I think it demonstrates that the php buildpack supports applications which shell out to the CLI.

**Comment by till** [comment]
Thanks, that got me on the right track. Sorry for the noise, so much to learn. 🙈 
https://github.com/till/php-buildpack-console-example

What are the situations where the `launcher` is used? Interactive sessions?

As in, I see the following in the image's `ENTRYPOINT`:

```
❯ docker inspect php-console| jq -r '.[0].Config.Entrypoint'
[
  "/cnb/process/web"
]
```

**Comment by till** [comment]
Thanks for all the help with this. I am closing this as it works.
